read_dir: /path/to/reads
tmp_dir: /path/to/tmp
sample: [MFD00392,MFD05176,MFD08497,MFD02416,MFD05684,MFD01721]
subset_gb: [20,40,60,80,100]
datatypes: [reads,contigs]
conda_exe: /path/to/env/Miniforge3-23.3.1-1-Linux-x86_64/etc/profile.d/conda.sh
env_rasusa: /path/to/env/rasusa_2.0.0
env_mmlong2: /path/to/env/mmlong2-lite_1.0.2
env_cramino: /path/to/env/cramino_0.14.1
env_kaiju: /path/to/env/kaiju_1.10.1
env_nanoq: /path/to/env/nanoq_0.10.0
env_barrnap: /path/to/env/barrnap_0.9
env_melon: /path/to/env/melon_0.2.0
env_singlem: /path/to/env/singlem_0.18.0
env_tiara: /path/to/env/tiara_1.0.3
env_jellyfish: /path/to/env/jellyfish_2.2.10
env_longshot: /path/to/env/longshot_1.0.0
db_kaiju: /path/to/db/kaiju_db_nr_euk_2023-05-10
db_melon: /path/to/db/melon_0.2.0/database 
db_singlem: /path/to/db/singlem_0.18.0/S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb
