read_dir: /projects/microflora_danica/deep_metagenomes/reads
tmp_dir: /projects/microflora_danica/deep_metagenomes/tmp
sample: [MFD00392,MFD05176,MFD08497,MFD02416,MFD05684,MFD01721]
subset_gb: [20,40,60,80,100]
datatypes: [reads,contigs]
conda_exe: /usr/local/Miniforge3-23.3.1-1-Linux-x86_64/etc/profile.d/conda.sh
env_rasusa: /home/bio.aau.dk/gg40ls/env/rasusa_2.0.0
env_mmlong2: /projects/microflora_danica/mmlong2/conda/mmlong2-lite_1.0.2
env_cramino: /home/bio.aau.dk/gg40ls/env/cramino_0.14.1
env_kaiju: /home/bio.aau.dk/gg40ls/env/kaiju_1.10.1
env_nanoq: /home/bio.aau.dk/gg40ls/env/nanoq_0.10.0
env_barrnap: /home/bio.aau.dk/gg40ls/env/barrnap_0.9
env_melon: /home/bio.aau.dk/gg40ls/env/melon_0.2.0
env_singlem: /home/bio.aau.dk/gg40ls/env/singlem_0.18.0
env_tiara: /home/bio.aau.dk/gg40ls/env/tiara_1.0.3
env_jellyfish: /home/bio.aau.dk/gg40ls/env/jellyfish_2.2.10
env_longshot: /home/bio.aau.dk/gg40ls/env/longshot_1.0.0
db_kaiju: /home/bio.aau.dk/gg40ls/general/custom/kaiju_db_nr_euk_2023-05-10
db_melon: /home/bio.aau.dk/gg40ls/general/custom/melon_0.2.0/database 
db_singlem: /home/bio.aau.dk/gg40ls/general/custom/singlem_0.18.0/S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb
